/**
 * This class file was automatically generated by jASN1 v1.11.2 (http://www.beanit.com)
 */

package ccsds.sle.transfer.service.rocf.outgoing.pdus;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;
import com.beanit.jasn1.ber.types.string.*;

import ccsds.sle.transfer.service.bind.types.SleBindInvocation;
import ccsds.sle.transfer.service.bind.types.SleBindReturn;
import ccsds.sle.transfer.service.bind.types.SlePeerAbort;
import ccsds.sle.transfer.service.bind.types.SleUnbindInvocation;
import ccsds.sle.transfer.service.bind.types.SleUnbindReturn;
import ccsds.sle.transfer.service.common.pdus.SleAcknowledgement;
import ccsds.sle.transfer.service.common.pdus.SleScheduleStatusReportReturn;
import ccsds.sle.transfer.service.common.types.Credentials;
import ccsds.sle.transfer.service.common.types.IntUnsignedLong;
import ccsds.sle.transfer.service.common.types.InvokeId;
import ccsds.sle.transfer.service.common.types.SpaceLinkDataUnit;
import ccsds.sle.transfer.service.common.types.Time;
import ccsds.sle.transfer.service.rocf.structures.AntennaId;
import ccsds.sle.transfer.service.rocf.structures.CarrierLockStatus;
import ccsds.sle.transfer.service.rocf.structures.DiagnosticRocfGet;
import ccsds.sle.transfer.service.rocf.structures.DiagnosticRocfStart;
import ccsds.sle.transfer.service.rocf.structures.FrameSyncLockStatus;
import ccsds.sle.transfer.service.rocf.structures.LockStatus;
import ccsds.sle.transfer.service.rocf.structures.Notification;
import ccsds.sle.transfer.service.rocf.structures.RocfGetParameter;
import ccsds.sle.transfer.service.rocf.structures.RocfProductionStatus;
import ccsds.sle.transfer.service.rocf.structures.SymbolLockStatus;

public class RocfTransferDataInvocation implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static class PrivateAnnotation implements BerType, Serializable {

		private static final long serialVersionUID = 1L;

		public byte[] code = null;
		private BerNull null_ = null;
		private BerOctetString notNull = null;
		
		public PrivateAnnotation() {
		}

		public PrivateAnnotation(byte[] code) {
			this.code = code;
		}

		public void setNull(BerNull null_) {
			this.null_ = null_;
		}

		public BerNull getNull() {
			return null_;
		}

		public void setNotNull(BerOctetString notNull) {
			this.notNull = notNull;
		}

		public BerOctetString getNotNull() {
			return notNull;
		}

		public int encode(OutputStream reverseOS) throws IOException {

			if (code != null) {
				for (int i = code.length - 1; i >= 0; i--) {
					reverseOS.write(code[i]);
				}
				return code.length;
			}

			int codeLength = 0;
			if (notNull != null) {
				codeLength += notNull.encode(reverseOS, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 1
				reverseOS.write(0x81);
				codeLength += 1;
				return codeLength;
			}
			
			if (null_ != null) {
				codeLength += null_.encode(reverseOS, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 0
				reverseOS.write(0x80);
				codeLength += 1;
				return codeLength;
			}
			
			throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
		}

		public int decode(InputStream is) throws IOException {
			return decode(is, null);
		}

		public int decode(InputStream is, BerTag berTag) throws IOException {

			int codeLength = 0;
			BerTag passedTag = berTag;

			if (berTag == null) {
				berTag = new BerTag();
				codeLength += berTag.decode(is);
			}

			if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 0)) {
				null_ = new BerNull();
				codeLength += null_.decode(is, false);
				return codeLength;
			}

			if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 1)) {
				notNull = new BerOctetString();
				codeLength += notNull.decode(is, false);
				return codeLength;
			}

			if (passedTag != null) {
				return 0;
			}

			throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
		}

		public void encodeAndSave(int encodingSizeGuess) throws IOException {
			ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
			encode(reverseOS);
			code = reverseOS.getArray();
		}

		public String toString() {
			StringBuilder sb = new StringBuilder();
			appendAsString(sb, 0);
			return sb.toString();
		}

		public void appendAsString(StringBuilder sb, int indentLevel) {

			if (null_ != null) {
				sb.append("null_: ").append(null_);
				return;
			}

			if (notNull != null) {
				sb.append("notNull: ").append(notNull);
				return;
			}

			sb.append("<none>");
		}

	}

	public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);

	public byte[] code = null;
	private Credentials invokerCredentials = null;
	private Time earthReceiveTime = null;
	private AntennaId antennaId = null;
	private BerInteger dataLinkContinuity = null;
	private PrivateAnnotation privateAnnotation = null;
	private SpaceLinkDataUnit data = null;
	
	public RocfTransferDataInvocation() {
	}

	public RocfTransferDataInvocation(byte[] code) {
		this.code = code;
	}

	public void setInvokerCredentials(Credentials invokerCredentials) {
		this.invokerCredentials = invokerCredentials;
	}

	public Credentials getInvokerCredentials() {
		return invokerCredentials;
	}

	public void setEarthReceiveTime(Time earthReceiveTime) {
		this.earthReceiveTime = earthReceiveTime;
	}

	public Time getEarthReceiveTime() {
		return earthReceiveTime;
	}

	public void setAntennaId(AntennaId antennaId) {
		this.antennaId = antennaId;
	}

	public AntennaId getAntennaId() {
		return antennaId;
	}

	public void setDataLinkContinuity(BerInteger dataLinkContinuity) {
		this.dataLinkContinuity = dataLinkContinuity;
	}

	public BerInteger getDataLinkContinuity() {
		return dataLinkContinuity;
	}

	public void setPrivateAnnotation(PrivateAnnotation privateAnnotation) {
		this.privateAnnotation = privateAnnotation;
	}

	public PrivateAnnotation getPrivateAnnotation() {
		return privateAnnotation;
	}

	public void setData(SpaceLinkDataUnit data) {
		this.data = data;
	}

	public SpaceLinkDataUnit getData() {
		return data;
	}

	public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		codeLength += data.encode(reverseOS, true);
		
		codeLength += privateAnnotation.encode(reverseOS);
		
		codeLength += dataLinkContinuity.encode(reverseOS, true);
		
		codeLength += antennaId.encode(reverseOS);
		
		codeLength += earthReceiveTime.encode(reverseOS);
		
		codeLength += invokerCredentials.encode(reverseOS);
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		subCodeLength += berTag.decode(is);
		invokerCredentials = new Credentials();
		subCodeLength += invokerCredentials.decode(is, berTag);
		subCodeLength += berTag.decode(is);
		
		earthReceiveTime = new Time();
		subCodeLength += earthReceiveTime.decode(is, berTag);
		subCodeLength += berTag.decode(is);
		
		antennaId = new AntennaId();
		subCodeLength += antennaId.decode(is, berTag);
		subCodeLength += berTag.decode(is);
		
		if (berTag.equals(BerInteger.tag)) {
			dataLinkContinuity = new BerInteger();
			subCodeLength += dataLinkContinuity.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		privateAnnotation = new PrivateAnnotation();
		subCodeLength += privateAnnotation.decode(is, berTag);
		subCodeLength += berTag.decode(is);
		
		if (berTag.equals(SpaceLinkDataUnit.tag)) {
			data = new SpaceLinkDataUnit();
			subCodeLength += data.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		sb.append("\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (invokerCredentials != null) {
			sb.append("invokerCredentials: ");
			invokerCredentials.appendAsString(sb, indentLevel + 1);
		}
		else {
			sb.append("invokerCredentials: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (earthReceiveTime != null) {
			sb.append("earthReceiveTime: ");
			earthReceiveTime.appendAsString(sb, indentLevel + 1);
		}
		else {
			sb.append("earthReceiveTime: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (antennaId != null) {
			sb.append("antennaId: ");
			antennaId.appendAsString(sb, indentLevel + 1);
		}
		else {
			sb.append("antennaId: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (dataLinkContinuity != null) {
			sb.append("dataLinkContinuity: ").append(dataLinkContinuity);
		}
		else {
			sb.append("dataLinkContinuity: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (privateAnnotation != null) {
			sb.append("privateAnnotation: ");
			privateAnnotation.appendAsString(sb, indentLevel + 1);
		}
		else {
			sb.append("privateAnnotation: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (data != null) {
			sb.append("data: ").append(data);
		}
		else {
			sb.append("data: <empty-required-field>");
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

