/**
 * This class file was automatically generated by jASN1 v1.11.2 (http://www.beanit.com)
 */

package ccsds.sle.transfer.service.common.types;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;
import com.beanit.jasn1.ber.types.string.*;


public class Time implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public byte[] code = null;
	private TimeCCSDS ccsdsFormat = null;
	private TimeCCSDSpico ccsdsPicoFormat = null;
	
	public Time() {
	}

	public Time(byte[] code) {
		this.code = code;
	}

	public void setCcsdsFormat(TimeCCSDS ccsdsFormat) {
		this.ccsdsFormat = ccsdsFormat;
	}

	public TimeCCSDS getCcsdsFormat() {
		return ccsdsFormat;
	}

	public void setCcsdsPicoFormat(TimeCCSDSpico ccsdsPicoFormat) {
		this.ccsdsPicoFormat = ccsdsPicoFormat;
	}

	public TimeCCSDSpico getCcsdsPicoFormat() {
		return ccsdsPicoFormat;
	}

	public int encode(OutputStream reverseOS) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			return code.length;
		}

		int codeLength = 0;
		if (ccsdsPicoFormat != null) {
			codeLength += ccsdsPicoFormat.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 1
			reverseOS.write(0x81);
			codeLength += 1;
			return codeLength;
		}
		
		if (ccsdsFormat != null) {
			codeLength += ccsdsFormat.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 0
			reverseOS.write(0x80);
			codeLength += 1;
			return codeLength;
		}
		
		throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
	}

	public int decode(InputStream is) throws IOException {
		return decode(is, null);
	}

	public int decode(InputStream is, BerTag berTag) throws IOException {

		int codeLength = 0;
		BerTag passedTag = berTag;

		if (berTag == null) {
			berTag = new BerTag();
			codeLength += berTag.decode(is);
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 0)) {
			ccsdsFormat = new TimeCCSDS();
			codeLength += ccsdsFormat.decode(is, false);
			return codeLength;
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 1)) {
			ccsdsPicoFormat = new TimeCCSDSpico();
			codeLength += ccsdsPicoFormat.decode(is, false);
			return codeLength;
		}

		if (passedTag != null) {
			return 0;
		}

		throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		if (ccsdsFormat != null) {
			sb.append("ccsdsFormat: ").append(ccsdsFormat);
			return;
		}

		if (ccsdsPicoFormat != null) {
			sb.append("ccsdsPicoFormat: ").append(ccsdsPicoFormat);
			return;
		}

		sb.append("<none>");
	}

}

