/**
 * This class file was automatically generated by jASN1 v1.11.2 (http://www.beanit.com)
 */

package ccsds.sle.transfer.service.raf.structures;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;
import com.beanit.jasn1.ber.types.string.*;

import ccsds.sle.transfer.service.common.pdus.ReportingCycle;
import ccsds.sle.transfer.service.common.types.DeliveryMode;
import ccsds.sle.transfer.service.common.types.Diagnostics;
import ccsds.sle.transfer.service.common.types.IntPosLong;
import ccsds.sle.transfer.service.common.types.IntPosShort;
import ccsds.sle.transfer.service.common.types.ParameterName;
import ccsds.sle.transfer.service.common.types.Time;

public class LockStatusReport implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);

	public byte[] code = null;
	private Time time = null;
	private CarrierLockStatus carrierLockStatus = null;
	private LockStatus subcarrierLockStatus = null;
	private SymbolLockStatus symbolSyncLockStatus = null;
	
	public LockStatusReport() {
	}

	public LockStatusReport(byte[] code) {
		this.code = code;
	}

	public void setTime(Time time) {
		this.time = time;
	}

	public Time getTime() {
		return time;
	}

	public void setCarrierLockStatus(CarrierLockStatus carrierLockStatus) {
		this.carrierLockStatus = carrierLockStatus;
	}

	public CarrierLockStatus getCarrierLockStatus() {
		return carrierLockStatus;
	}

	public void setSubcarrierLockStatus(LockStatus subcarrierLockStatus) {
		this.subcarrierLockStatus = subcarrierLockStatus;
	}

	public LockStatus getSubcarrierLockStatus() {
		return subcarrierLockStatus;
	}

	public void setSymbolSyncLockStatus(SymbolLockStatus symbolSyncLockStatus) {
		this.symbolSyncLockStatus = symbolSyncLockStatus;
	}

	public SymbolLockStatus getSymbolSyncLockStatus() {
		return symbolSyncLockStatus;
	}

	public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		codeLength += symbolSyncLockStatus.encode(reverseOS, true);
		
		codeLength += subcarrierLockStatus.encode(reverseOS, true);
		
		codeLength += carrierLockStatus.encode(reverseOS, true);
		
		codeLength += time.encode(reverseOS);
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		subCodeLength += berTag.decode(is);
		time = new Time();
		subCodeLength += time.decode(is, berTag);
		subCodeLength += berTag.decode(is);
		
		if (berTag.equals(CarrierLockStatus.tag)) {
			carrierLockStatus = new CarrierLockStatus();
			subCodeLength += carrierLockStatus.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(LockStatus.tag)) {
			subcarrierLockStatus = new LockStatus();
			subCodeLength += subcarrierLockStatus.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(SymbolLockStatus.tag)) {
			symbolSyncLockStatus = new SymbolLockStatus();
			subCodeLength += symbolSyncLockStatus.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		sb.append("\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (time != null) {
			sb.append("time: ");
			time.appendAsString(sb, indentLevel + 1);
		}
		else {
			sb.append("time: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (carrierLockStatus != null) {
			sb.append("carrierLockStatus: ").append(carrierLockStatus);
		}
		else {
			sb.append("carrierLockStatus: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (subcarrierLockStatus != null) {
			sb.append("subcarrierLockStatus: ").append(subcarrierLockStatus);
		}
		else {
			sb.append("subcarrierLockStatus: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (symbolSyncLockStatus != null) {
			sb.append("symbolSyncLockStatus: ").append(symbolSyncLockStatus);
		}
		else {
			sb.append("symbolSyncLockStatus: <empty-required-field>");
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

